import "./globals.css";
import { inter, soraSans } from "@/styles/fonts";
import { Metadata } from "next";
import { METADATA } from "@/constant/metadata";
import { ThemeProviderContext } from "@/app/providers";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: `${METADATA.creator} | Personal Website`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={soraSans.className}>
        <ThemeProviderContext> 
          <Navbar/>
          {children}
        </ThemeProviderContext>
      </body>
    </html>
  );
}
